baseURL = "https://kaomi.life/"
languageCode = "en-us"
title = "Kaomi Life"
theme = "beautifulhugo"
disqusShortname = "kaomi-life"


[Params]
#    subtitle = "Build a beautiful and simple website in minutes"
    logo = "bee_512.png"
    favicon = "favicon.ico"
    dateFormat = "January 2, 2006"
    comments = true
    commit = false
    rss = true
    readingTime = true
    useHLJS = true
    addThis = "ra-5a9f5acc20c648d7"

[Author]
    name = "Ashley Nelson"


[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1